apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aliyun-nsg-updater.fullname" . }}-config
  labels:
    {{- include "aliyun-nsg-updater.labels" . | nindent 4 }}
    {{- with .Values.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    aliyun:
      access_key_id: {{ .Values.aliyun.accessKeyId | quote }}
      access_key_secret: {{ .Values.aliyun.accessKeySecret | quote }}
      region_id: {{ .Values.aliyun.regionId | quote }}
    rules:
{{ toYaml .Values.rules | indent 6 }}
