{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aliyun-nsg-updater.fullname" . }}-credentials
  labels:
    {{- include "aliyun-nsg-updater.labels" . | nindent 4 }}
    {{- with .Values.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  ALIYUN_ACCESS_KEY_ID: {{ .Values.aliyun.accessKeyId | quote }}
  ALIYUN_ACCESS_KEY_SECRET: {{ .Values.aliyun.accessKeySecret | quote }}
  ALIYUN_REGION_ID: {{ .Values.aliyun.regionId | quote }}
{{- end }}
